name: Release
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "Automated Version Bump"
          git config user.email "gh-action-bump-version@users.noreply.github.com"
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform fmt -check -recursive -diff
      - run: terraform validate
      - run: echo "##[set-output name=version;]$(jq -r '.version' module.json)"
        id: current_version
      - uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.current_version.outputs.version}}
          release_name: ${{ steps.current_version.outputs.version }}
      - uses: "scaffoldly/github-action-bump-version-terraform-module@master"
        with:
          tag-prefix: ""
