name: Pull Request
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: |
          git config user.name "Automated Version Bump"
          git config user.email "gh-action-bump-version@users.noreply.github.com"
      - uses: hashicorp/setup-terraform@v1
      # TODO - uses: scaffoldly/terraform-plan-release@v1
      - run: |
          terraform init
          terraform workspace new live || true
          terraform workspace select live
      - uses: andstor/file-existence-action@v1
        id: terraform_state
        with:
          files: "terraform.tfstate.d/live/terraform.tfstate.gpg"
      - run: |
          mkdir -p terraform.tfstate.d/live
          cp misc/empty.tfstate terraform.tfstate.d/live/terraform.tfstate
          gpg --batch -c --passphrase "$BOOTSTRAP_GITHUB_TOKEN" terraform.tfstate.d/live/terraform.tfstate
          rm terraform.tfstate.d/live/terraform.tfstate
          git add terraform.tfstate.d/live/terraform.tfstate.gpg
          git commit -a -m "Add state file"
          git push
        if: steps.terraform_state.outputs.files_exists == 'false'
        env:
          BOOTSTRAP_GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_GITHUB_TOKEN }}
      - run: gpg --batch -d --passphrase "$BOOTSTRAP_GITHUB_TOKEN" -o terraform.tfstate.d/live/terraform.tfstate terraform.tfstate.d/live/terraform.tfstate.gpg
        env:
          BOOTSTRAP_GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_GITHUB_TOKEN }}
      - run: terraform plan -no-color -out planfile
        id: plan
        env:
          TF_VAR_BOOTSTRAP_GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ```
            ${{ join(steps.plan.outputs.*, '\n')}}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
