name: Commit to Master
on:
  push:
    branches:
      - master
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform workspace new ${GITHUB_REF##*/} || true
      - run: terraform workspace select ${GITHUB_REF##*/}
      - run: terraform plan -out "planfile"
        env:
          TF_ENV_BOOTSTRAP_GITHUB_TOKEN: ${{ secrets.BOOTSTRAP_GITHUB_TOKEN }}
